server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/stores/**
        - id: shipper-service
          uri: lb://shipper-service
          predicates:
            - Path=/shippers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
